title: IMB Archi Ergo
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_type: boxed
style: classic
palette: green
mode: light
base_font: serif
header:
  title: IMB Archi Ergo
  logo: images/imb_logo.jpg
  logo_alt: IMB Archi Ergo
  has_secondary_nav: true
  secondary_nav_links:
    - label: Prestations
      url: /prestations
      style: link  
    - label: Références
      url: /blog
      style: link
    - label: Contact
      url: /contact
      style: link
footer:
  has_social: true
  social_links:
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/inas-mikhail-403635b4'
      style: link
      has_icon: true
      icon: linkedin
      icon_position: center
      new_window: true
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>.
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'http://localhost:4000'
